### ISSUE TITLE
Translation bug - Game settings screen

### ISSUE THREAD

**Issue by caiorsantanna** [theblitzapp/Blitz-Bugs#6]
# Translation bug - Game settings screen

Hi, there is a translation bug, at least in pt-br (portuguese - brazil) mode, in the game settings section, on settings screen, when we choose the TFT options, check it out:

<p align="center">
<img src="https://user-images.githubusercontent.com/26316189/79817910-e88ce880-835c-11ea-8a3f-954d84482aeb.png" width="500px" />
</p>

Code:
```
 key 'settings.tft (pt)' returned an object instead of string.
```

Edit: I just test it out with other languages, same bug.

**Comment by 1337MARCEL** [comment]
Fixed in latest release, thank you!
